"""The Pro blocks of the three standalone guides are generated by pro_blocks.py
from pro_cases.py. These tests pin the page structure, the case inventory and
the unified build against that generator."""
import re
import unittest
from pathlib import Path

import pro_blocks
import pro_cases as pc

ROOT = Path(__file__).resolve().parents[1]
GUIDES = {
    'a2': (ROOT / '2x2/rubiks-2x2-guide.html', 'guide2pro', 'g2p', 'cube2-pro-v1'),
    'a3': (ROOT / '3x3/rubiks-3x3-guide.html', 'guide3pro', 'g3p', 'cube3-pro-v1'),
    'py': (ROOT / 'pyraminx/rubiks-pyraminx-guide.html', 'guidepypro', 'gpp', 'pyraminx-pro-v1'),
}
PAGES = {
    'a2': ['intro', '1', '2', '3', '4', 'drill', 'algs'],
    'a3': ['intro', '1', '2', '3', '4', 'drill', 'algs', 'summary'],
    'py': ['intro', '1', '2', '3', 'drill', 'algs'],
}
MARK, END = '<div class="mode mode-pro">', '</div><!-- /mode-pro -->'


def pro_block(html):
    return html.split(MARK, 1)[1].split(END, 1)[0]


class TestGeneratedBlocks(unittest.TestCase):
    def test_standalone_pro_blocks_equal_the_generator_output(self):
        for cube, (path, root, ns, key) in GUIDES.items():
            html = path.read_text(encoding='utf-8')
            self.assertEqual(html.count(MARK), 1, cube)
            self.assertEqual(MARK + pro_block(html) + END, pro_blocks.render(cube), cube)

    def test_unified_pro_blocks_equal_the_standalone_ones_after_prefixing(self):
        unified = (ROOT / 'cube-solving.html').read_text(encoding='utf-8')
        blocks = re.findall(re.escape(MARK) + r'(.*?)' + re.escape(END), unified, re.S)
        self.assertEqual(len(blocks), 3)
        for (cube, (path, root, ns, key)), built in zip(GUIDES.items(), blocks):
            built = re.sub(r'id="%s-([^"]+)"' % cube, r'id="\1"', built)
            built = re.sub(r'href="#%s-([^"]+)"' % cube, r'href="#\1"', built)
            self.assertEqual(built, pro_block(path.read_text(encoding='utf-8')), cube)

    def test_namespaces_storage_keys_and_activity_classes_are_isolated(self):
        for cube, (path, root, ns, key) in GUIDES.items():
            block = pro_block(path.read_text(encoding='utf-8'))
            self.assertIn('<div class="%s"' % root, block)
            self.assertIn('data-%s-key="%s"' % (ns, key), block)
            self.assertIn('<style data-%s-styles>' % root, block)
            self.assertIn('<script data-%s-runtime>' % root, block)
            self.assertIn('body.%s-active' % ns, block)
            for other_cube, (_, other_root, other_ns, other_key) in GUIDES.items():
                if other_cube != cube:
                    self.assertNotIn(other_root, block, (cube, other_root))
                    self.assertNotIn(other_ns + '-', block, (cube, other_ns))
                    self.assertNotIn(other_key, block, (cube, other_key))
            self.assertNotIn('guidepro', block)
            self.assertNotIn('"gp-', block)
            self.assertNotIn('—', block, 'em dash in %s Pro block' % cube)

    def test_pages_steps_and_done_boxes(self):
        for cube, (path, root, ns, key) in GUIDES.items():
            block = pro_block(path.read_text(encoding='utf-8'))
            self.assertEqual(re.findall(r'data-%s-page="([^"]+)"' % ns, block), PAGES[cube], cube)
            steps = [p for p in PAGES[cube] if p.isdigit()]
            self.assertEqual(re.findall(r'<input[^>]*data-%s-done="([^"]+)"' % ns, block), steps, cube)
            self.assertIn('data-%s-steps="%d"' % (ns, len(steps)), block)
            for marker in ('data-%s-help' % ns, 'data-%s-menu' % ns, 'data-%s-prev' % ns, 'data-%s-next' % ns,
                           'data-%s-drill-set' % ns, 'data-%s-total' % ns, '%s-goal' % ns, '%s-grip' % ns, '%s-check' % ns):
                self.assertIn(marker, block, (cube, marker))
            for step in steps:
                page = re.search(r'data-%s-page="%s"(.*?)</section>' % (ns, step), block, re.S).group(1)
                for marker in ('%s-goal' % ns, '%s-grip' % ns, '%s-check' % ns, 'data-%s-done="%s"' % (ns, step)):
                    self.assertIn(marker, page, (cube, step, marker))

    def test_case_cards_have_consistent_ids_pictures_and_learned_boxes(self):
        for cube, (path, root, ns, key) in GUIDES.items():
            block = pro_block(path.read_text(encoding='utf-8'))
            cards = re.findall(r'<div class="%s-case( %s-case-text)?" data-%s-case="([^"]+)" data-%s-sets="([^"]+)">(.*?)<label class="%s-learned">'
                               % (ns, ns, ns, ns, ns), block, re.S)
            self.assertTrue(cards, cube)
            algs = {}
            for text_only, cid, sets, body in cards:
                alg = re.search(r'data-alg="([^"]+)"', body).group(1)
                algs.setdefault(cid, set()).add(alg)
                self.assertTrue(sets.strip(), cid)
                if text_only:
                    self.assertNotIn('<figure', body, cid)
                else:
                    self.assertIn('<figure class="dg"', body, cid)
                self.assertIn('data-%s-learned="%s"' % (ns, cid), block)
            for cid, found in algs.items():
                self.assertEqual(len(found), 1, 'case %s has different algorithms: %r' % (cid, found))

    def test_case_inventory_matches_the_methods(self):
        def unique_ids(block, ns, group_key_prefix):
            ids = set()
            for g in re.findall(r'<details class="%s-group"[^>]*>(.*?)</details>' % ns, block, re.S):
                key = re.search(r'data-%s-group-count="([^"]+)"' % ns, g).group(1)
                if key.startswith(group_key_prefix):
                    ids.update(re.findall(r'data-%s-case="([^"]+)"' % ns, g))
            return ids
        a3 = pro_block(GUIDES['a3'][0].read_text(encoding='utf-8'))
        self.assertEqual(len(unique_ids(a3, 'g3p', 'oll57:')), 57)
        self.assertEqual(len(unique_ids(a3, 'g3p', 'pll21:')), 21)
        self.assertEqual(len(unique_ids(a3, 'g3p', 'f2l:')), 40)
        self.assertEqual(len(set(re.findall(r'data-g3p-case="([^"]+)"', a3))), 57 + 21 + 40 + 3)
        a2 = pro_block(GUIDES['a2'][0].read_text(encoding='utf-8'))
        self.assertEqual(len(unique_ids(a2, 'g2p', 'cll:')), 42)
        self.assertEqual(len(set(re.findall(r'data-g2p-case="([^"]+)"', a2))), 7 + 5 + 40)
        py = pro_block(GUIDES['py'][0].read_text(encoding='utf-8'))
        self.assertEqual(len(set(re.findall(r'data-gpp-case="([^"]+)"', py))), 7)

    def test_pictures_come_from_the_simulator_data(self):
        a3 = pro_block(GUIDES['a3'][0].read_text(encoding='utf-8'))
        for d in pc.OLL:
            self.assertIn('data-kind="top" data-c="%s" data-b="%s" data-f="%s" data-l="%s" data-r="%s"'
                          % (d['c'], d['b'], d['f'], d['l'], d['r']), a3, d['id'])
        for d in pc.F2L:
            self.assertIn('data-kind="f2l" data-u="%s" data-f="%s" data-r="%s"' % (d['u'], d['f'], d['r']), a3, d['id'])
        a2 = pro_block(GUIDES['a2'][0].read_text(encoding='utf-8'))
        for d in pc.CLL:
            self.assertIn('data-c="%s" data-b="%s" data-f="%s" data-l="%s" data-r="%s"'
                          % (d['c'], d['b'], d['f'], d['l'], d['r']), a2, d['id'])
        for d in pc.PBL:
            b = d['bottom']
            self.assertIn('data-c="%s" data-b="%s" data-f="%s" data-l="%s" data-r="%s"'
                          % (b['c'], b['b'], b['f'], b['l'], b['r']), a2, d['id'])

    def test_intro_terms_are_used_later_in_the_block(self):
        for cube, (path, root, ns, key) in GUIDES.items():
            block = pro_block(path.read_text(encoding='utf-8'))
            intro = re.search(r'data-%s-page="intro"(.*?)</section>' % ns, block, re.S).group(1)
            rest = block.replace(intro, '').lower()
            terms = re.search(r'Vārdi, kas parādīsies tālāk</h3>\s*<ul>(.*?)</ul>', intro, re.S).group(1)
            for term in re.findall(r'<li><strong>([^<]+)</strong>', terms):
                word = re.split(r'[ ,/]', term)[0].lower()
                self.assertIn(word, rest, (cube, term))

    def test_pro_navs_link_to_existing_pro_pages(self):
        for cube, (path, root, ns, key) in GUIDES.items():
            html = path.read_text(encoding='utf-8')
            nav = re.search(r'<nav class="steps pro-nav".*?</nav>', html, re.S).group(0)
            block = pro_block(html)
            for href in re.findall(r'href="#([^"]+)"', nav):
                if href == 'nota':
                    continue
                self.assertIn('id="%s"' % href, block, (cube, href))


if __name__ == '__main__':
    unittest.main()
